# Generated by Django 5.0.2 on 2024-04-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
