# Generated by Django 5.0.2 on 2024-04-07 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0005_taskslabels_tasks_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(blank=True, through='tasks.TasksLabels', to='labels.labels', verbose_name='labels'),
        ),
        migrations.AlterField(
            model_name='taskslabels',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labels.labels', verbose_name='label'),
        ),
    ]
