# Generated by Django 5.0.2 on 2024-04-11 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_statuses_options_alter_statuses_name'),
        ('tasks', '0006_alter_tasks_labels_alter_taskslabels_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statuses.statuses', verbose_name='status'),
        ),
    ]
